### PR TITLE
Updated docs related to openvino 

### LINKED ISSUE #25: Update the OpenVINO document after WasmEdge 0.13.2 released
# Overview
In the 0.13.2 release, OpenVINO bumped its version from 2021 to 2023, which changed the installation guide. See https://github.com/WasmEdge/docs/issues/136

We should refer to the corresponding website instead of maintaining a standalone installation guide in this repo.

# Details

1. Modify the README to use the OpenVINO document from the WasmEdge/docs repo/website
2. Remove everything related to OpenVINO 2021.

### PR DESCRIPTION
**Pull request by Mash707**
resolves #25

### CODE REVIEW

**Comment by juntao** [comment]
Hello, I am a [code review bot](https://github.com/flows-network/github-pr-summary/) on [flows.network](https://flows.network/).

It could take a few minutes for me to analyze this PR. Relax, grab a cup of coffee and check back later. Thanks!

**Comment by Mash707** [comment]
Hii @hydai could you please review the the PR. Also I have a question regarding the `install_openvino.sh`, what is the purpose of the code written from line 19 to 28 https://github.com/second-state/WasmEdge-WASINN-examples/blob/4f7ff0a7327602e4f513bab428495309e889a250/scripts/install_openvino.sh#L19-L28

**Comment by hydai** [comment]
> Hii @hydai could you please review the the PR. Also I have a question regarding the `install_openvino.sh`, what is the purpose of the code written from line 19 to 28?
> 
> https://github.com/second-state/WasmEdge-WASINN-examples/blob/4f7ff0a7327602e4f513bab428495309e889a250/scripts/install_openvino.sh#L19-L28

These lines are registering the OpenVINO libraries because the previous ones are using a script to set related environments. Since we don't need to do this anymore when using the official API repo, we can remove them.

**Comment by Mash707** [comment]
Hii @hydai I removed those lines. Should I add links to openvino official documents and wasmedge docs or the changes I made are enough?

**Comment by hydai** [comment]
> Hii @hydai I removed those lines. Should we add links to openvino official documents and wasmedge docs or the changes I made are enough?

Yes, please

**Comment by Mash707** [comment]
I have added links to the official openvino docs in the readme files

**Comment by Mash707** [comment]
I have added links in the readme files of each example also. Should we keep the docs links in each readme file ?

**Review by hydai — APPROVED** [review]
LGTM. @apepkuss PTAL.

**Comment by hydai** [comment]
Looks like there is a conflict between this branch and the master branch. Please fix the conflicts.
CleanShot 2023-07-26 at 01 48 21

**Comment by Mash707** [comment]
> Looks like there is a conflict between this branch and the master branch. Please fix the conflicts. CleanShot 2023-07-26 at 01 48 21

is this for me to fix ?

**Comment by hydai** [comment]
You may need to pull/rebase your branch to fix the conflicts.

**Comment by Mash707** [comment]
> You may need to pull/rebase your branch to fix the conflicts.

I tried pulling and rebasing my branch with master branch but the conflict is not fixed.
image
I used this for reference regarding pulling and rebasing https://stackoverflow.com/questions/7929369/how-to-rebase-local-branch-onto-remote-master.

**Comment by Mash707** [comment]
Hii @hydai I have resolved the conflict. The PR is now ready to be merged.

**Comment by apepkuss** [comment]
@Mash707 Please check the failed CI workflows and resolve the failures. Thanks!

**Comment by Mash707** [comment]
Hii @apepkuss , The workflow should work now because previously it was using wasmedge version `0.13.1` . I changed it to the latest release `0.13.2`. The install script for openvino was updated in the `0.13.2` release.

**Pull request merged**
