### PR TITLE
[Examples] add Pytorch image demo

### PR DESCRIPTION
**Pull request by gusye1234**
add an image classification demo for PyTorch backend

### CODE REVIEW

**Comment by juntao** [comment]
Shall we use `wasmedge-nn` in this example?

**Comment by apepkuss** [comment]
Hi @gusye1234 

I recently created [`feat-wasmedge-wasi-nn` branch](feat-wasmedge-wasi-nn) in `wasmedge-nn` to support PyTorch. If you have interest in it, you can introduce the repo in your PyTorch example project.

**Comment by gusye1234** [comment]
> Hi @gusye1234
> 
> I recently created [`feat-wasmedge-wasi-nn` branch](feat-wasmedge-wasi-nn) in `wasmedge-nn` to support PyTorch. If you have interest in it, you can introduce the repo in your PyTorch example project.

Will try it on!

**Comment by gusye1234** [comment]
Hi @apepkuss , seem like you didn't sign your commits: 32a0cc92a4ab6922dd9558ae7583cd001601d1a5, b0b7ae634e7836a54b773aa67d2ba6519de40b5d, 96e5118e85401d58ed84af50bdcd7cf09387bfbf, and that blocks this PR's CI cause I rebased on the master branch😂.

**Comment by apepkuss** [comment]
@gusye1234 I checked the previous PR #7, #8, and also #10, in which all commits were signed. The snapshot below shows the original branch for creating PR #10, in which all commits were signed-off. 

image

Do we have to use a GPG key to sign the commits?

@juntao Is it required to sign off all commits with a GPG key?

**Comment by hydai** [comment]
@gusye1234 @apepkuss Looks like the `signed commit is required` is enabled, which asks developers should use gpg sign for every commit. I just disabled it. So it should be fine now.

**Comment by apepkuss** [comment]
@hydai Thanks a lot!

**Review by q82419 — CHANGES_REQUESTED** [review]
Please upload the `.pt` and the steps to generate the model file.

**Review by q82419 — APPROVED** [review]

**Pull request merged**
