### PR TITLE
docs: Add note for install errors and solutions

### PR DESCRIPTION
**Pull request by katopz**
ref https://github.com/second-state/WasmEdge-WASINN-examples/issues/39

### CODE REVIEW

**Comment by juntao** [comment]
Hello, I am a [code review bot](https://github.com/flows-network/github-pr-summary/) on [flows.network](https://flows.network/).

It could take a few minutes for me to analyze this PR. Relax, grab a cup of coffee and check back later. Thanks!

**Review by juntao — APPROVED** [review]
Thanks!

**Comment by hydai** [comment]
Hi @katopz 
Please add the following sections before the `unknown option`:

```
[2023-10-02 14:30:31.227] [error] loading failed: invalid path, Code: 0x20
[2023-10-02 14:30:31.227] [error]     load library failed:libblas.so.3: cannot open shared object file: No such file or directory
[2023-10-02 14:30:31.227] [error] loading failed: invalid path, Code: 0x20
[2023-10-02 14:30:31.227] [error]     load library failed:libblas.so.3: cannot open shared object file: No such file or directory
```

**Review by hydai — APPROVED** [review]

**Comment by hydai** [comment]
Thanks!

**Pull request merged**
