### PR TITLE
[Examples] Update the wasi-nn crate dependency to 0.4.0

### PR DESCRIPTION
**Pull request by yanghaku**
This PR update the wasi-nn crate dependency to 0.4.0. (This PR only changes the rust source code and README files, it does not change the wasm binary files.)

### CODE REVIEW

**Comment by juntao** [comment]
Hello, I am a [code review bot](https://github.com/flows-network/github-pr-summary/) on [flows.network](https://flows.network/).

It could take a few minutes for me to analyze this PR. Relax, grab a cup of coffee and check back later. Thanks!

**Comment by juntao** [comment]
Hi, I made changes to the TFLite example in this PR

https://github.com/second-state/WasmEdge-WASINN-examples/pull/22

It is not just the WASI NN update, but also overall directory structure and CI updates.  I planned to merge it when all examples are updated.

Can you revert the TFLite changes in this PR and I will merge it. Thanks!

**Comment by yanghaku** [comment]
OK, Now I have deleted the TFLite changes in the commits.

**Comment by juntao** [comment]
Related to issue #21

**Pull request merged**
