### PR TITLE
Set metadata when building graph

### PR DESCRIPTION
**Pull request by dm4**
- Set metadata when building graph
- Set options only if it is specified

This PR depends on:
- https://github.com/second-state/wasmedge-wasi-nn/pull/2
- https://github.com/WasmEdge/WasmEdge/pull/3031

### CODE REVIEW

**Comment by juntao** [comment]
Hello, I am a [code review bot](https://github.com/flows-network/github-pr-summary/) on [flows.network](https://flows.network/).

It could take a few minutes for me to analyze this PR. Relax, grab a cup of coffee and check back later. Thanks!

**Comment by hydai** [comment]
Hi @dm4
I think we should use a `dev` branch for the unreleased features. Once the release assets are updated, then we merge it back to `master`.

**Comment by dm4** [comment]
> Hi @dm4 I think we should use a `dev` branch for the unreleased features. Once the release assets are updated, then we merge it back to `master`.

Okay, I have just changed the target branch to the `dev` branch.

**Comment by dm4** [comment]
@hydai, according to our previous discussion, I have made updates to the README and have kept the previous metadata setting code as a comment.

**Review by hydai — APPROVED** [review]

**Pull request merged**
